version: "3.9"
services:
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
  app:
    container_name: task-manager
    restart: always
    build: .
    ports:
      - "80:3000"
    links:
      - mongo
